### ISSUE TITLE
Incompatibility with supplementaries on connector 1.20.1

### ISSUE THREAD

**Issue by styyylo** [Heccology/Bountiful-Fares#28]
when I try to make a world with this mod installed to my modpack, for 1.20.1 with either version 1.2.1 or 1.2.0, the game will save world and crash immediately as I'm supposed to spawn in any older version of the mod and I simply cant get the world to reach 100% made anyway.

I sorted out all the mods that could be causing this issue and it only happens with Bountiful Fares is installed, and not when it isn't

the error is descried as: Exception in server tick loop

net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$BadModError: Some OTHER mod loaded the Sheets class to early, causing modded banner patterns and sherds textures to not include modded ones.
Refusing to proceed further. Do Not report this to Supplementaries

the crash looks like this:

at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.clientStuff(VibeChecker.java:70) ~[supplementaries-1.20-2.8.15.jar%23453!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:30) ~[supplementaries-1.20-2.8.15.jar%23453!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onServerTick(ServerEventsForge.java:228) ~[supplementaries-1.20-2.8.15.jar%23453!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onServerTick_LevelTickEvent.invoke(.dynamic) ~[supplementaries-1.20-2.8.15.jar%23453!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925) ~[forge-1.20.1-47.2.17-universal.jar%23473!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890) ~[client-1.20.1-20230612.114412-srg.jar%23468!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:goodending.mixins.json:MinecraftServerMixin from mod goodending,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23468!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:goodending.mixins.json:MinecraftServerMixin from mod goodending,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23468!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin from mod blueprint,pl:mixin:APP:mixins.essential.json:server.integrated.Mixin_FixDefaultOpPermissionLevel from mod (unknown),pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23468!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:goodending.mixins.json:MinecraftServerMixin from mod goodending,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23468!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:surveyor.mixins.json:MixinMinecraftServer from mod surveyor,pl:mixin:APP:goodending.mixins.json:MinecraftServerMixin from mod goodending,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack from mod (unknown),pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule from mod (unknown),pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by Poopooracoocoo** [comment]
#18
